//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java_Remote_Controller.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://i.fauxpen/")]
    public partial class IllegalAccessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://i.fauxpen/")]
    public partial class ogiComponent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool checkedField;
        
        private string nameField;
        
        private string textField;
        
        private string typeField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://i.fauxpen/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://i.fauxpen/", ConfigurationName="ServiceReference1.RemoteControlService")]
    public interface RemoteControlService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlByLabelRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlByLabelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IllegalAccessException), Action="http://i.fauxpen/RemoteControlService/GetControlByLabel/Fault/IllegalAccessExcept" +
            "ion", Name="IllegalAccessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetControlByLabelResponse GetControlByLabel(Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlByLabelRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlByLabelResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlByLabelResponse> GetControlByLabelAsync(Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetStringRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetStringResponse GetString(Java_Remote_Controller.ServiceReference1.GetStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetStringRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetStringResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetStringResponse> GetStringAsync(Java_Remote_Controller.ServiceReference1.GetStringRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetFormsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetFormsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetFormsResponse GetForms(Java_Remote_Controller.ServiceReference1.GetFormsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetFormsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetFormsResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsResponse> GetFormsAsync(Java_Remote_Controller.ServiceReference1.GetFormsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlsListRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlsListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IllegalAccessException), Action="http://i.fauxpen/RemoteControlService/GetControlsList/Fault/IllegalAccessExceptio" +
            "n", Name="IllegalAccessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetControlsListResponse GetControlsList(Java_Remote_Controller.ServiceReference1.GetControlsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlsListRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlsListResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsListResponse> GetControlsListAsync(Java_Remote_Controller.ServiceReference1.GetControlsListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/ScreenShotRequest", ReplyAction="http://i.fauxpen/RemoteControlService/ScreenShotResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IOException), Action="http://i.fauxpen/RemoteControlService/ScreenShot/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.ScreenShotResponse ScreenShot(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/ScreenShotRequest", ReplyAction="http://i.fauxpen/RemoteControlService/ScreenShotResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ScreenShotResponse> ScreenShotAsync(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IllegalAccessException), Action="http://i.fauxpen/RemoteControlService/GetControl/Fault/IllegalAccessException", Name="IllegalAccessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetControlResponse GetControl(Java_Remote_Controller.ServiceReference1.GetControlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlResponse> GetControlAsync(Java_Remote_Controller.ServiceReference1.GetControlRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/ClickButtonRequest", ReplyAction="http://i.fauxpen/RemoteControlService/ClickButtonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IllegalAccessException), Action="http://i.fauxpen/RemoteControlService/ClickButton/Fault/IllegalAccessException", Name="IllegalAccessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Java_Remote_Controller.ServiceReference1.ClickButtonResponse ClickButton(Java_Remote_Controller.ServiceReference1.ClickButtonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/ClickButtonRequest", ReplyAction="http://i.fauxpen/RemoteControlService/ClickButtonResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ClickButtonResponse> ClickButtonAsync(Java_Remote_Controller.ServiceReference1.ClickButtonRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/SetControlRequest", ReplyAction="http://i.fauxpen/RemoteControlService/SetControlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IllegalAccessException), Action="http://i.fauxpen/RemoteControlService/SetControl/Fault/IllegalAccessException", Name="IllegalAccessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Java_Remote_Controller.ServiceReference1.SetControlResponse SetControl(Java_Remote_Controller.ServiceReference1.SetControlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/SetControlRequest", ReplyAction="http://i.fauxpen/RemoteControlService/SetControlResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.SetControlResponse> SetControlAsync(Java_Remote_Controller.ServiceReference1.SetControlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/PressButtonRequest", ReplyAction="http://i.fauxpen/RemoteControlService/PressButtonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PressButton();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/PressButtonRequest", ReplyAction="http://i.fauxpen/RemoteControlService/PressButtonResponse")]
        System.Threading.Tasks.Task PressButtonAsync();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetFormsArrayRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetFormsArrayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetFormsArrayResponse GetFormsArray(Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetFormsArrayRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetFormsArrayResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsArrayResponse> GetFormsArrayAsync(Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetControlsResponse GetControls(Java_Remote_Controller.ServiceReference1.GetControlsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlsResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsResponse> GetControlsAsync(Java_Remote_Controller.ServiceReference1.GetControlsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlByLabel", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlByLabelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public GetControlByLabelRequest() {
        }
        
        public GetControlByLabelRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlByLabelResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlByLabelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Java_Remote_Controller.ServiceReference1.ogiComponent @return;
        
        public GetControlByLabelResponse() {
        }
        
        public GetControlByLabelResponse(Java_Remote_Controller.ServiceReference1.ogiComponent @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetString", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetStringRequest {
        
        public GetStringRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStringResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetStringResponse() {
        }
        
        public GetStringResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetForms", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetFormsRequest {
        
        public GetFormsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFormsResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetFormsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetFormsResponse() {
        }
        
        public GetFormsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlsList", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public GetControlsListRequest() {
        }
        
        public GetControlsListRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlsListResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public GetControlsListResponse() {
        }
        
        public GetControlsListResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ScreenShot", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class ScreenShotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public ScreenShotRequest() {
        }
        
        public ScreenShotRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ScreenShotResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class ScreenShotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public ScreenShotResponse() {
        }
        
        public ScreenShotResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControl", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public GetControlRequest() {
        }
        
        public GetControlRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Java_Remote_Controller.ServiceReference1.ogiComponent @return;
        
        public GetControlResponse() {
        }
        
        public GetControlResponse(Java_Remote_Controller.ServiceReference1.ogiComponent @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClickButton", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class ClickButtonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public ClickButtonRequest() {
        }
        
        public ClickButtonRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClickButtonResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class ClickButtonResponse {
        
        public ClickButtonResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetControl", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class SetControlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public SetControlRequest() {
        }
        
        public SetControlRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetControlResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class SetControlResponse {
        
        public SetControlResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFormsArray", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetFormsArrayRequest {
        
        public GetFormsArrayRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFormsArrayResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetFormsArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public GetFormsArrayResponse() {
        }
        
        public GetFormsArrayResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControls", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public GetControlsRequest() {
        }
        
        public GetControlsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlsResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetControlsResponse() {
        }
        
        public GetControlsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RemoteControlServiceChannel : Java_Remote_Controller.ServiceReference1.RemoteControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteControlServiceClient : System.ServiceModel.ClientBase<Java_Remote_Controller.ServiceReference1.RemoteControlService>, Java_Remote_Controller.ServiceReference1.RemoteControlService {
        
        public RemoteControlServiceClient() {
        }
        
        public RemoteControlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteControlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteControlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteControlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetControlByLabelResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlByLabel(Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest request) {
            return base.Channel.GetControlByLabel(request);
        }
        
        public Java_Remote_Controller.ServiceReference1.ogiComponent GetControlByLabel(string arg0, string arg1) {
            Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Java_Remote_Controller.ServiceReference1.GetControlByLabelResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlByLabel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlByLabelResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlByLabelAsync(Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest request) {
            return base.Channel.GetControlByLabelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlByLabelResponse> GetControlByLabelAsync(string arg0, string arg1) {
            Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlByLabelRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlByLabelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetStringResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetString(Java_Remote_Controller.ServiceReference1.GetStringRequest request) {
            return base.Channel.GetString(request);
        }
        
        public string GetString() {
            Java_Remote_Controller.ServiceReference1.GetStringRequest inValue = new Java_Remote_Controller.ServiceReference1.GetStringRequest();
            Java_Remote_Controller.ServiceReference1.GetStringResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetStringResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetStringAsync(Java_Remote_Controller.ServiceReference1.GetStringRequest request) {
            return base.Channel.GetStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetStringResponse> GetStringAsync() {
            Java_Remote_Controller.ServiceReference1.GetStringRequest inValue = new Java_Remote_Controller.ServiceReference1.GetStringRequest();
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetFormsResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetForms(Java_Remote_Controller.ServiceReference1.GetFormsRequest request) {
            return base.Channel.GetForms(request);
        }
        
        public string GetForms() {
            Java_Remote_Controller.ServiceReference1.GetFormsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetFormsRequest();
            Java_Remote_Controller.ServiceReference1.GetFormsResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetForms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetFormsAsync(Java_Remote_Controller.ServiceReference1.GetFormsRequest request) {
            return base.Channel.GetFormsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsResponse> GetFormsAsync() {
            Java_Remote_Controller.ServiceReference1.GetFormsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetFormsRequest();
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetFormsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetControlsListResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlsList(Java_Remote_Controller.ServiceReference1.GetControlsListRequest request) {
            return base.Channel.GetControlsList(request);
        }
        
        public string[] GetControlsList(string arg0) {
            Java_Remote_Controller.ServiceReference1.GetControlsListRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlsListRequest();
            inValue.arg0 = arg0;
            Java_Remote_Controller.ServiceReference1.GetControlsListResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlsList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsListResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlsListAsync(Java_Remote_Controller.ServiceReference1.GetControlsListRequest request) {
            return base.Channel.GetControlsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsListResponse> GetControlsListAsync(string arg0) {
            Java_Remote_Controller.ServiceReference1.GetControlsListRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlsListRequest();
            inValue.arg0 = arg0;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.ScreenShotResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.ScreenShot(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request) {
            return base.Channel.ScreenShot(request);
        }
        
        public byte[] ScreenShot(string arg0) {
            Java_Remote_Controller.ServiceReference1.ScreenShotRequest inValue = new Java_Remote_Controller.ServiceReference1.ScreenShotRequest();
            inValue.arg0 = arg0;
            Java_Remote_Controller.ServiceReference1.ScreenShotResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).ScreenShot(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ScreenShotResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.ScreenShotAsync(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request) {
            return base.Channel.ScreenShotAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ScreenShotResponse> ScreenShotAsync(string arg0) {
            Java_Remote_Controller.ServiceReference1.ScreenShotRequest inValue = new Java_Remote_Controller.ServiceReference1.ScreenShotRequest();
            inValue.arg0 = arg0;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).ScreenShotAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetControlResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControl(Java_Remote_Controller.ServiceReference1.GetControlRequest request) {
            return base.Channel.GetControl(request);
        }
        
        public Java_Remote_Controller.ServiceReference1.ogiComponent GetControl(string arg0, string arg1) {
            Java_Remote_Controller.ServiceReference1.GetControlRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Java_Remote_Controller.ServiceReference1.GetControlResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlAsync(Java_Remote_Controller.ServiceReference1.GetControlRequest request) {
            return base.Channel.GetControlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlResponse> GetControlAsync(string arg0, string arg1) {
            Java_Remote_Controller.ServiceReference1.GetControlRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.ClickButtonResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.ClickButton(Java_Remote_Controller.ServiceReference1.ClickButtonRequest request) {
            return base.Channel.ClickButton(request);
        }
        
        public void ClickButton(string arg0, string arg1) {
            Java_Remote_Controller.ServiceReference1.ClickButtonRequest inValue = new Java_Remote_Controller.ServiceReference1.ClickButtonRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Java_Remote_Controller.ServiceReference1.ClickButtonResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).ClickButton(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ClickButtonResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.ClickButtonAsync(Java_Remote_Controller.ServiceReference1.ClickButtonRequest request) {
            return base.Channel.ClickButtonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ClickButtonResponse> ClickButtonAsync(string arg0, string arg1) {
            Java_Remote_Controller.ServiceReference1.ClickButtonRequest inValue = new Java_Remote_Controller.ServiceReference1.ClickButtonRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).ClickButtonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.SetControlResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.SetControl(Java_Remote_Controller.ServiceReference1.SetControlRequest request) {
            return base.Channel.SetControl(request);
        }
        
        public void SetControl(string arg0, string arg1, string arg2) {
            Java_Remote_Controller.ServiceReference1.SetControlRequest inValue = new Java_Remote_Controller.ServiceReference1.SetControlRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Java_Remote_Controller.ServiceReference1.SetControlResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).SetControl(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.SetControlResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.SetControlAsync(Java_Remote_Controller.ServiceReference1.SetControlRequest request) {
            return base.Channel.SetControlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.SetControlResponse> SetControlAsync(string arg0, string arg1, string arg2) {
            Java_Remote_Controller.ServiceReference1.SetControlRequest inValue = new Java_Remote_Controller.ServiceReference1.SetControlRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).SetControlAsync(inValue);
        }
        
        public void PressButton() {
            base.Channel.PressButton();
        }
        
        public System.Threading.Tasks.Task PressButtonAsync() {
            return base.Channel.PressButtonAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetFormsArrayResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetFormsArray(Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest request) {
            return base.Channel.GetFormsArray(request);
        }
        
        public string[] GetFormsArray() {
            Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest inValue = new Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest();
            Java_Remote_Controller.ServiceReference1.GetFormsArrayResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetFormsArray(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsArrayResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetFormsArrayAsync(Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest request) {
            return base.Channel.GetFormsArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsArrayResponse> GetFormsArrayAsync() {
            Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest inValue = new Java_Remote_Controller.ServiceReference1.GetFormsArrayRequest();
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetFormsArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetControlsResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControls(Java_Remote_Controller.ServiceReference1.GetControlsRequest request) {
            return base.Channel.GetControls(request);
        }
        
        public string GetControls(string arg0) {
            Java_Remote_Controller.ServiceReference1.GetControlsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlsRequest();
            inValue.arg0 = arg0;
            Java_Remote_Controller.ServiceReference1.GetControlsResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControls(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlsAsync(Java_Remote_Controller.ServiceReference1.GetControlsRequest request) {
            return base.Channel.GetControlsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsResponse> GetControlsAsync(string arg0) {
            Java_Remote_Controller.ServiceReference1.GetControlsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlsRequest();
            inValue.arg0 = arg0;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlsAsync(inValue);
        }
    }
}
