//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java_Remote_Controller.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://i.fauxpen/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://i.fauxpen/", ConfigurationName="ServiceReference1.RemoteControlService")]
    public interface RemoteControlService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/onMessageRequest", ReplyAction="http://i.fauxpen/RemoteControlService/onMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.onMessageResponse onMessage(Java_Remote_Controller.ServiceReference1.onMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/onMessageRequest", ReplyAction="http://i.fauxpen/RemoteControlService/onMessageResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.onMessageResponse> onMessageAsync(Java_Remote_Controller.ServiceReference1.onMessageRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetStringRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetStringResponse GetString(Java_Remote_Controller.ServiceReference1.GetStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetStringRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetStringResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetStringResponse> GetStringAsync(Java_Remote_Controller.ServiceReference1.GetStringRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetFormsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetFormsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetFormsResponse GetForms(Java_Remote_Controller.ServiceReference1.GetFormsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetFormsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetFormsResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsResponse> GetFormsAsync(Java_Remote_Controller.ServiceReference1.GetFormsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/ScreenShotRequest", ReplyAction="http://i.fauxpen/RemoteControlService/ScreenShotResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Java_Remote_Controller.ServiceReference1.IOException), Action="http://i.fauxpen/RemoteControlService/ScreenShot/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.ScreenShotResponse ScreenShot(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/ScreenShotRequest", ReplyAction="http://i.fauxpen/RemoteControlService/ScreenShotResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ScreenShotResponse> ScreenShotAsync(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Java_Remote_Controller.ServiceReference1.GetControlsResponse GetControls(Java_Remote_Controller.ServiceReference1.GetControlsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/GetControlsRequest", ReplyAction="http://i.fauxpen/RemoteControlService/GetControlsResponse")]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsResponse> GetControlsAsync(Java_Remote_Controller.ServiceReference1.GetControlsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/PressButtonRequest", ReplyAction="http://i.fauxpen/RemoteControlService/PressButtonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PressButton();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://i.fauxpen/RemoteControlService/PressButtonRequest", ReplyAction="http://i.fauxpen/RemoteControlService/PressButtonResponse")]
        System.Threading.Tasks.Task PressButtonAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onMessage", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class onMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public onMessageRequest() {
        }
        
        public onMessageRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="onMessageResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class onMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public onMessageResponse() {
        }
        
        public onMessageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetString", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetStringRequest {
        
        public GetStringRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStringResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetStringResponse() {
        }
        
        public GetStringResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetForms", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetFormsRequest {
        
        public GetFormsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFormsResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetFormsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetFormsResponse() {
        }
        
        public GetFormsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ScreenShot", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class ScreenShotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public ScreenShotRequest() {
        }
        
        public ScreenShotRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ScreenShotResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class ScreenShotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public ScreenShotResponse() {
        }
        
        public ScreenShotResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControls", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public GetControlsRequest() {
        }
        
        public GetControlsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetControlsResponse", WrapperNamespace="http://i.fauxpen/", IsWrapped=true)]
    public partial class GetControlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://i.fauxpen/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetControlsResponse() {
        }
        
        public GetControlsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RemoteControlServiceChannel : Java_Remote_Controller.ServiceReference1.RemoteControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteControlServiceClient : System.ServiceModel.ClientBase<Java_Remote_Controller.ServiceReference1.RemoteControlService>, Java_Remote_Controller.ServiceReference1.RemoteControlService {
        
        public RemoteControlServiceClient() {
        }
        
        public RemoteControlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteControlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteControlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteControlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.onMessageResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.onMessage(Java_Remote_Controller.ServiceReference1.onMessageRequest request) {
            return base.Channel.onMessage(request);
        }
        
        public string onMessage(string arg0) {
            Java_Remote_Controller.ServiceReference1.onMessageRequest inValue = new Java_Remote_Controller.ServiceReference1.onMessageRequest();
            inValue.arg0 = arg0;
            Java_Remote_Controller.ServiceReference1.onMessageResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).onMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.onMessageResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.onMessageAsync(Java_Remote_Controller.ServiceReference1.onMessageRequest request) {
            return base.Channel.onMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.onMessageResponse> onMessageAsync(string arg0) {
            Java_Remote_Controller.ServiceReference1.onMessageRequest inValue = new Java_Remote_Controller.ServiceReference1.onMessageRequest();
            inValue.arg0 = arg0;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).onMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetStringResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetString(Java_Remote_Controller.ServiceReference1.GetStringRequest request) {
            return base.Channel.GetString(request);
        }
        
        public string GetString() {
            Java_Remote_Controller.ServiceReference1.GetStringRequest inValue = new Java_Remote_Controller.ServiceReference1.GetStringRequest();
            Java_Remote_Controller.ServiceReference1.GetStringResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetStringResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetStringAsync(Java_Remote_Controller.ServiceReference1.GetStringRequest request) {
            return base.Channel.GetStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetStringResponse> GetStringAsync() {
            Java_Remote_Controller.ServiceReference1.GetStringRequest inValue = new Java_Remote_Controller.ServiceReference1.GetStringRequest();
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetFormsResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetForms(Java_Remote_Controller.ServiceReference1.GetFormsRequest request) {
            return base.Channel.GetForms(request);
        }
        
        public string GetForms() {
            Java_Remote_Controller.ServiceReference1.GetFormsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetFormsRequest();
            Java_Remote_Controller.ServiceReference1.GetFormsResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetForms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetFormsAsync(Java_Remote_Controller.ServiceReference1.GetFormsRequest request) {
            return base.Channel.GetFormsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetFormsResponse> GetFormsAsync() {
            Java_Remote_Controller.ServiceReference1.GetFormsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetFormsRequest();
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetFormsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.ScreenShotResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.ScreenShot(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request) {
            return base.Channel.ScreenShot(request);
        }
        
        public byte[] ScreenShot(string arg0) {
            Java_Remote_Controller.ServiceReference1.ScreenShotRequest inValue = new Java_Remote_Controller.ServiceReference1.ScreenShotRequest();
            inValue.arg0 = arg0;
            Java_Remote_Controller.ServiceReference1.ScreenShotResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).ScreenShot(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ScreenShotResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.ScreenShotAsync(Java_Remote_Controller.ServiceReference1.ScreenShotRequest request) {
            return base.Channel.ScreenShotAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.ScreenShotResponse> ScreenShotAsync(string arg0) {
            Java_Remote_Controller.ServiceReference1.ScreenShotRequest inValue = new Java_Remote_Controller.ServiceReference1.ScreenShotRequest();
            inValue.arg0 = arg0;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).ScreenShotAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Java_Remote_Controller.ServiceReference1.GetControlsResponse Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControls(Java_Remote_Controller.ServiceReference1.GetControlsRequest request) {
            return base.Channel.GetControls(request);
        }
        
        public string GetControls(string arg0) {
            Java_Remote_Controller.ServiceReference1.GetControlsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlsRequest();
            inValue.arg0 = arg0;
            Java_Remote_Controller.ServiceReference1.GetControlsResponse retVal = ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControls(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsResponse> Java_Remote_Controller.ServiceReference1.RemoteControlService.GetControlsAsync(Java_Remote_Controller.ServiceReference1.GetControlsRequest request) {
            return base.Channel.GetControlsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Java_Remote_Controller.ServiceReference1.GetControlsResponse> GetControlsAsync(string arg0) {
            Java_Remote_Controller.ServiceReference1.GetControlsRequest inValue = new Java_Remote_Controller.ServiceReference1.GetControlsRequest();
            inValue.arg0 = arg0;
            return ((Java_Remote_Controller.ServiceReference1.RemoteControlService)(this)).GetControlsAsync(inValue);
        }
        
        public void PressButton() {
            base.Channel.PressButton();
        }
        
        public System.Threading.Tasks.Task PressButtonAsync() {
            return base.Channel.PressButtonAsync();
        }
    }
}
